package Lab8;

import Lab8.Library;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//Edit the source  (e.g. write an comment), and build it again.
public class Library {
	
	public static void main(String arg[]) {
		Library lib = new Library();
		if(lib.someLibraryMethod()) {
			System.out.println("When there is  a fire, commit and push.");
		}
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
